export enum Duration {
  FIFTEEN_MINUTES = 15,
  THIRTY_MINUTES = 30,
  FORTY_FIVE_MINUTES = 45,
  ONE_HOUR = 60,
  ONE_HOUR_AND_FIFTEEN_MINUTES = 75,
  ONE_HOUR_AND_THIRTY_MINUTES = 90,
  ONE_HOUR_AND_FORTY_FIVE_MINUTES = 105,
  TWO_HOURS = 120,
}
